<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2O8ecsb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2O8ecsb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2O8ecsb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2O8ecsb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2O8ecsb\App_KernelDevDebugContainer([
    'container.build_hash' => '2O8ecsb',
    'container.build_id' => '7791fdbb',
    'container.build_time' => 1698214523,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2O8ecsb');
